### ISSUE TITLE
Errors in job.rb when running job

### ISSUE THREAD

**Issue by openluopworld** [intel/lkp-tests#10]
Hi, the command `lkp split jobs/hackbench.yaml` gets the following error on my Linux 3.13.0-24-generic x86-64.
```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /home/luopeng/lkp-tests-master/lib/job.rb:392: unknown type of %string (SyntaxError)
        available_programs %i(workload_elements monitors)
                              ^
/home/luopeng/lkp-tests-master/lib/job.rb:392: syntax error, unexpected $end, expecting keyword_end
        available_programs %i(workload_elements monitors)
                              ^
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/luopeng/lkp-tests-master/sbin/split-job:5:in `<main>'
```
The `lkp install` runs well and the dependencies have been installed. So what may be the problem? Thanks.

**Comment by openluopworld** [comment]
I have tried 2.0 and 2.3, but both did not work.
```
/usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- git (LoadError)
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/luopeng/lkp-tests-master/lib/git_ext.rb:7:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/luopeng/lkp-tests-master/lib/lkp_git.rb:16:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/luopeng/lkp-tests-master/lib/result.rb:6:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/luopeng/lkp-tests-master/lib/job.rb:7:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/luopeng/lkp-tests-master/sbin/split-job:5:in `<main>'
```

Here are the steps:
1) Download the source code of 2.0.0-p648 ( or 2.3.6)
2) install
```sh
    ./configure # It failed to config some files, but I'm not sure whether it is the reason
    make
    make install
````
3) After installation, the ruby has been updated to the higher version.

**Comment by rli9** [comment]
sorry for non complete doc, here it misses required ruby gems after initial problems is solved.

you can try below. And it may still miss other gems, and we will follow up to fix in case Gemfile has issue.
```
gem install bundler
cd path/to/lkp-tests
bundle install
```

**Comment by openluopworld** [comment]
Get it. Thanks so much for your fast reply and help.
