### ISSUE TITLE
ncompare, _rm broken on latest lkp-tests

### ISSUE THREAD

**Issue by bssrikanth** [intel/lkp-tests#128]
One a machine where I have latest build of lkp-tests [head-> 93e671505f1793446a1c50f120a47b732bce6974], I see ncompare being broken,

```
# lkp ncompare -s commit=5.16.2-v5.16 -s commit=5.15.2-build41 -a  -k
Traceback (most recent call last):
        17: from /home/LKP/lkp-tests/sbin/ncompare:6:in `<main>'
        16: from /home/LKP/lkp-tests/lib/compare.rb:1150:in `compare'
        15: from /home/LKP/lkp-tests/lib/compare.rb:1140:in `parse_argv'
        14: from /home/LKP/lkp-tests/lib/compare.rb:1140:in `map'
        13: from /home/LKP/lkp-tests/lib/compare.rb:1142:in `block in parse_argv'
        12: from /home/LKP/lkp-tests/lib/compare.rb:1142:in `to_a'
        11: from /home/LKP/lkp-tests/lib/nresult_root.rb:391:in `each'
        10: from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `mrt_table_set'
         9: from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `new'
         8: from /home/LKP/lkp-tests/lib/nresult_root.rb:278:in `initialize'
         7: from /home/LKP/lkp-tests/lib/nresult_root.rb:248:in `open'
         6: from /home/LKP/lkp-tests/lib/data_store.rb:834:in `open'
         5: from /home/LKP/lkp-tests/lib/data_store.rb:241:in `open'
         4: from /home/LKP/lkp-tests/lib/common.rb:24:in `block in add_cached_method'
         3: from /home/LKP/lkp-tests/lib/common.rb:24:in `new'
         2: from /home/LKP/lkp-tests/lib/data_store.rb:67:in `initialize'
         1: from /home/LKP/lkp-tests/lib/data_store.rb:79:in `load'
/home/LKP/lkp-tests/lib/data_store.rb:84:in `from_data': undefined method `each' for nil:NilClass (NoMethodError)
```

Same ebizzy results if I remote merge and do a ncompare on another server [where lkp-tests head -> 6ccdc974b68db4bab9e6bb49994e581ce26824bc] it works well:

```
$ lkp ncompare -s commit=5.16.2-v5.16 -s commit=5.15.2-build41 -a  -k
=========================================================================================
compiler/duration/iterations/kconfig/nr_threads/rootfs/tbox_group/testcase:
  gcc/10s/10x/defconfig/200%/rhel/souparnika/ebizzy

commit:
  5.16.2-v5.16
  5.15.2-build41

5.16.2-v5.16              5.15.2-build41
---------------- ---------------------------
         %stddev     %change         %stddev
             \          |                \
   2884351            -1.2%    2850900        ebizzy.throughput
     18656            -7.3%      17297        ebizzy.throughput.per_thread.max
      7752            +2.9%       7979        ebizzy.throughput.per_thread.min
      0.10           -22.1%       0.08        ebizzy.throughput.per_thread.stddev_percent
  28843510            -1.2%   28509008        ebizzy.workload
```

I am running on RHEL 8.4, with ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]

**Comment by bssrikanth** [comment]
Also seeing issues with lkp _rm:
```
ssh root@dellj853host echo yes | lkp _rm dellj853host rhel ebizzy v5.16'
23:18:34  /home/LKP/lkp-tests/lib/data_store.rb:84:in `from_data': undefined method `each' for nil:NilClass (NoMethodError)
23:18:34  	from /home/LKP/lkp-tests/lib/data_store.rb:79:in `load'
23:18:34  	from /home/LKP/lkp-tests/lib/data_store.rb:67:in `initialize'
23:18:34  	from /home/LKP/lkp-tests/lib/common.rb:24:in `new'
23:18:34  	from /home/LKP/lkp-tests/lib/common.rb:24:in `block in add_cached_method'
23:18:34  	from /home/LKP/lkp-tests/lib/data_store.rb:241:in `open'
23:18:34  	from /home/LKP/lkp-tests/lib/data_store.rb:834:in `open'
23:18:34  	from /home/LKP/lkp-tests/lib/nresult_root.rb:248:in `open'
23:18:34  	from /home/LKP/lkp-tests/lib/nresult_root.rb:278:in `initialize'
23:18:34  	from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `new'
23:18:34  	from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `mrt_table_set'
23:18:34  	from /home/LKP/lkp-tests/lib/result_root.rb:384:in `delete_mrt'
23:18:34  	from /home/LKP/lkp-tests/lkp-exec/delete_mrts:12:in `block in main'
23:18:34  	from /home/LKP/lkp-tests/lkp-exec/delete_mrts:8:in `each_line'
23:18:34  	from /home/LKP/lkp-tests/lkp-exec/delete_mrts:8:in `main'
23:18:34  	from /home/LKP/lkp-tests/lkp-exec/delete_mrts:16:in `<main>'
23:18:34  Done
```

**Comment by bssrikanth** [comment]
I see a comment in #129 that some of regressions are fixed, so will retry with latest branch.

**Comment by bssrikanth** [comment]
> I see a comment in #129 that some of regressions are fixed, so will retry with latest branch.

I saw that fix posted #129  was for split-job, I still see issues with ncompare and _rm on latest build:

```
[root@dellj853host LKP]# lkp ncompare -s commit=5.15.2-v5.15 -s commit=5.16.2-v5.16 -a -k
Traceback (most recent call last):
        17: from /home/LKP/lkp-tests/sbin/ncompare:6:in `<main>'
        16: from /home/LKP/lkp-tests/lib/compare.rb:1150:in `compare'
        15: from /home/LKP/lkp-tests/lib/compare.rb:1140:in `parse_argv'
        14: from /home/LKP/lkp-tests/lib/compare.rb:1140:in `map'
        13: from /home/LKP/lkp-tests/lib/compare.rb:1142:in `block in parse_argv'
        12: from /home/LKP/lkp-tests/lib/compare.rb:1142:in `to_a'
        11: from /home/LKP/lkp-tests/lib/nresult_root.rb:391:in `each'
        10: from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `mrt_table_set'
         9: from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `new'
         8: from /home/LKP/lkp-tests/lib/nresult_root.rb:278:in `initialize'
         7: from /home/LKP/lkp-tests/lib/nresult_root.rb:248:in `open'
         6: from /home/LKP/lkp-tests/lib/data_store.rb:834:in `open'
         5: from /home/LKP/lkp-tests/lib/data_store.rb:241:in `open'
         4: from /home/LKP/lkp-tests/lib/common.rb:24:in `block in add_cached_method'
         3: from /home/LKP/lkp-tests/lib/common.rb:24:in `new'
         2: from /home/LKP/lkp-tests/lib/data_store.rb:67:in `initialize'
         1: from /home/LKP/lkp-tests/lib/data_store.rb:79:in `load'
/home/LKP/lkp-tests/lib/data_store.rb:84:in `from_data': undefined method `each' for nil:NilClass (NoMethodError)
[root@dellj853host LKP]# lkp _rm dellj853host rhel ebizzy v5.16
The command will remove the following 1 _result_root:
/lkp/result/ebizzy/10s-10x-200%/dellj853host/rhel/defconfig/gcc/5.16.2-v5.16/
!!! Do you really want to do that? [No/yes]: yes
Traceback (most recent call last):
        15: from /home/LKP/lkp-tests/lkp-exec/delete_mrts:16:in `<main>'
        14: from /home/LKP/lkp-tests/lkp-exec/delete_mrts:8:in `main'
        13: from /home/LKP/lkp-tests/lkp-exec/delete_mrts:8:in `each_line'
        12: from /home/LKP/lkp-tests/lkp-exec/delete_mrts:12:in `block in main'
        11: from /home/LKP/lkp-tests/lib/result_root.rb:384:in `delete_mrt'
        10: from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `mrt_table_set'
         9: from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `new'
         8: from /home/LKP/lkp-tests/lib/nresult_root.rb:278:in `initialize'
         7: from /home/LKP/lkp-tests/lib/nresult_root.rb:248:in `open'
         6: from /home/LKP/lkp-tests/lib/data_store.rb:834:in `open'
         5: from /home/LKP/lkp-tests/lib/data_store.rb:241:in `open'
         4: from /home/LKP/lkp-tests/lib/common.rb:24:in `block in add_cached_method'
         3: from /home/LKP/lkp-tests/lib/common.rb:24:in `new'
         2: from /home/LKP/lkp-tests/lib/data_store.rb:67:in `initialize'
         1: from /home/LKP/lkp-tests/lib/data_store.rb:79:in `load'
/home/LKP/lkp-tests/lib/data_store.rb:84:in `from_data': undefined method `each' for nil:NilClass (NoMethodError)
Done

```

**Comment by xilabao** [comment]
Hi @bssrikanth, please update to the latest code and remove the `/lkp/data/mresult_root/linux_perf` directory, could you give it a shot?

**Comment by bssrikanth** [comment]
@xilabao  I update lkp to latest code. Still I see same issue after deleting the mentioned folder.

```
commit 5953709d9512933e335ddb8c297ec5dec2f82804 (origin/master, origin/HEAD)
Author: Chen Rong <rong.a.chen@intel.com>
Date:   Thu Mar 31 15:14:07 2022 +0800

    lib/data_store.rb: fix 297:in 'initialize': wrong number of arguments

    Traceback (most recent call last):
        6: from /lkp-tests/bin/run-local:165:in `<main>'
            5: from /lkp-tests/lib/nresult_root.rb:339:in `create_tables_layout'
            4: from /lkp-tests/lib/nresult_root.rb:257:in `create_layout'
            3: from /lkp-tests/lib/nresult_root.rb:243:in `create_layout'
            2: from /lkp-tests/lib/data_store.rb:225:in `add_index'
            1: from /lkp-tests/lib/data_store.rb:225:in `new'
    /lkp-tests/lib/data_store.rb:297:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)

    Fixes: 9e624cd599f5 (rubocop: cleanup Style/OptionalBooleanParameter offenses)
    Signed-off-by: Chen Rong <rong.a.chen@intel.com>
    Signed-off-by: Philip Li <philip.li@intel.com>
[root@dellj853host lkp-tests]# ls -alrt /lkp/data/mresult_root/linux_perf
ls: cannot access '/lkp/data/mresult_root/linux_perf': No such file or directory
[root@dellj853host lkp-tests]# lkp result ebizzy
/lkp/result/ebizzy/10s-10x-200%/dellj853host/rhel/defconfig/gcc/5.16.2-build43/0/
/lkp/result/ebizzy/10s-10x-200%/dellj853host/rhel/defconfig/gcc/5.16.2-v5.16/0/
[root@dellj853host lkp-tests]# lkp result hackbench
/lkp/result/hackbench/socket-8-threads-1600%/dellj853host/rhel/defconfig/gcc/5.16.2-build43/0/
/lkp/result/hackbench/socket-8-threads-1600%/dellj853host/rhel/defconfig/gcc/5.16.2-v5.16/0/
[root@dellj853host lkp-tests]# lkp ncompare -s testcase=hackbench/commit=5.16.2-build43 -s commit=5.16.2-v5.16 -a -k
Traceback (most recent call last):
        17: from /home/LKP/lkp-tests/sbin/ncompare:6:in `<main>'
        16: from /home/LKP/lkp-tests/lib/compare.rb:1150:in `compare'
        15: from /home/LKP/lkp-tests/lib/compare.rb:1140:in `parse_argv'
        14: from /home/LKP/lkp-tests/lib/compare.rb:1140:in `map'
        13: from /home/LKP/lkp-tests/lib/compare.rb:1142:in `block in parse_argv'
        12: from /home/LKP/lkp-tests/lib/compare.rb:1142:in `to_a'
        11: from /home/LKP/lkp-tests/lib/nresult_root.rb:388:in `each'
        10: from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `mrt_table_set'
         9: from /home/LKP/lkp-tests/lib/nresult_root.rb:345:in `new'
         8: from /home/LKP/lkp-tests/lib/nresult_root.rb:278:in `initialize'
         7: from /home/LKP/lkp-tests/lib/nresult_root.rb:248:in `open'
         6: from /home/LKP/lkp-tests/lib/data_store.rb:834:in `open'
         5: from /home/LKP/lkp-tests/lib/data_store.rb:241:in `open'
         4: from /home/LKP/lkp-tests/lib/common.rb:24:in `block in add_cached_method'
         3: from /home/LKP/lkp-tests/lib/common.rb:24:in `new'
         2: from /home/LKP/lkp-tests/lib/data_store.rb:67:in `initialize'
         1: from /home/LKP/lkp-tests/lib/data_store.rb:79:in `load'
/home/LKP/lkp-tests/lib/data_store.rb:84:in `from_data': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by xilabao** [comment]
@bssrikanth sorry, forgot to mention that old results are broken, you need to run `lkp merge  RESUTL_ROOT` , .e.g `lkp merge /lkp/result/hackbench/socket-8-threads-1600%/dellj853host/rhel/defconfig/gcc/5.16.2-build43/`

**Comment by bssrikanth** [comment]
> @bssrikanth sorry, forgot to mention that old results are broken, you need to run `lkp merge RESUTL_ROOT` , .e.g `lkp merge /lkp/result/hackbench/socket-8-threads-1600%/dellj853host/rhel/defconfig/gcc/5.16.2-build43/`

I had not used old results. The results folder I mentioned were freshly run with lkp installed from latest lkp-tests master. Hope that would not require lkp merge, please confirm.

**Comment by xilabao** [comment]
were these results generated (use`lkp run`) by new code after you removed `/lkp/data/mresult_root/linux_perf` ? @bssrikanth 

```
[root@dellj853host lkp-tests]# lkp result hackbench
/lkp/result/hackbench/socket-8-threads-1600%/dellj853host/rhel/defconfig/gcc/5.16.2-build43/0/
/lkp/result/hackbench/socket-8-threads-1600%/dellj853host/rhel/defconfig/gcc/5.16.2-v5.16/0/
```

**Comment by bssrikanth** [comment]
> were these results generated (use`lkp run`) by new code after you removed `/lkp/data/mresult_root/linux_perf` ? @bssrikanth 
> 
> ```
> [root@dellj853host lkp-tests]# lkp result hackbench
> /lkp/result/hackbench/socket-8-threads-1600%/dellj853host/rhel/defconfig/gcc/5.16.2-build43/0/
> /lkp/result/hackbench/socket-8-threads-1600%/dellj853host/rhel/defconfig/gcc/5.16.2-v5.16/0/
> ```

Yes that's correct, new results after removing that folder

**Comment by xilabao** [comment]
Below are my results, can you share the results in your environment?
```
# rm -r /lkp/data/mresult_root/linux_perf/
# lkp run hackbench-socket-8-threads-1600%.yaml
...
# tree /lkp/data/mresult_root/linux_perf/
/lkp/data/mresult_root/linux_perf/
|-- index
|   |-- DataStore::AxisIndex-commit
|   |   |-- 5.
|   |   |   `-- 5.13.0-37-generic
|   |   `-- index.yaml
|   `-- DataStore::DateIndex
|       |-- 2022-03-31
|       `-- index.yaml
|-- layout.yaml
`-- storage
    `-- 47
        `-- 47e5abb469d4de2df7a6f90d37279f42b57cedae -> /lkp/result/hackbench/socket-8-threads-1600%/rongch2-desk1/debian/defconfig/gcc-8/5.13.0-37-generic
# cat /lkp/data/mresult_root/linux_perf/layout.yaml
---
:maps: []
:comrpess_matrix:
```

**Comment by bssrikanth** [comment]
@xilabao below are more details,

Recreate steps with latest lkp code [ head -> 5953709d9512933e335ddb8c297ec5dec2f82804 ] , noticed that stack trace is a bit different compared to what I hit before:

	1. Remove linux_perf, before running hackbench with latest lkp:
	[root@dellj853host LKP]# rm -rf /lkp/data/mresult_root/linux_perf/
	
	2. Run hackbench
	[root@dellj853host LKP]# lkp run ./hackbench.yaml
	..
	3. Note linux_perf and layout contents:
	[root@dellj853host LKP]# tree /lkp/data/mresult_root/linux_perf/
	/lkp/data/mresult_root/linux_perf/
	├── index
	│   ├── DataStore::AxisIndex-commit
	│   │   ├── 5.
	│   │   │   └── 5.16.2-v5.16-amdsos
	│   │   └── index.yaml
	│   └── DataStore::DateIndex
	│       ├── 2022-04-01
	│       └── index.yaml
	├── layout.yaml
	└── storage
	    └── 1a
	        └── 1a8cbf91d684e86a2f6f46002783f0f677bd8c22 -> /lkp/result/hackbench/socket-1-threads-1600%/dellj853host.amd.com/rhel/defconfig/gcc/5.16.2-v5.16-amdsos
	
	7 directories, 5 files
	[root@dellj853host LKP]# cat /lkp/data/mresult_root/linux_perf/layout.yaml
	---
	:maps: []
	:comrpess_matrix:
	[root@dellj853host LKP]#

	4. Reboot to a different kernel, to run hackbench on it
	[root@dellj853host LKP]# lkp run ./hackbench.yaml
	..
	[root@dellj853host LKP]# tree /lkp/data/mresult_root/linux_perf/
	/lkp/data/mresult_root/linux_perf/
	├── index
	│   ├── DataStore::AxisIndex-commit
	│   │   ├── 5.
	│   │   │   ├── 5.15.2-v5.15-amdsos
	│   │   │   └── 5.16.2-v5.16-amdsos
	│   │   └── index.yaml
	│   └── DataStore::DateIndex
	│       ├── 2022-04-01
	│       └── index.yaml
	├── layout.yaml
	└── storage
	    ├── 1a
	    │   └── 1a8cbf91d684e86a2f6f46002783f0f677bd8c22 -> /lkp/result/hackbench/socket-1-threads-1600%/dellj853host.amd.com/rhel/defconfig/gcc/5.16.2-v5.16-amdsos
	    └── d3
	        └── d308f409c80b4bc52690854d1d6517ff0dfc952c -> /lkp/result/hackbench/socket-1-threads-1600%/dellj853host.amd.com/rhel/defconfig/gcc/5.15.2-v5.15-amdsos
	
	9 directories, 6 files
	[root@dellj853host LKP]# cat /lkp/data/mresult_root/linux_perf/layout.yaml
	---
	:maps: []
	:comrpess_matrix:

	5. Verify the results:
	[root@dellj853host LKP]# lkp result hackbench
	/lkp/result/hackbench/socket-1-threads-1600%/dellj853host.amd.com/rhel/defconfig/gcc/5.15.2-v5.15-amdsos/0/
	/lkp/result/hackbench/socket-1-threads-1600%/dellj853host.amd.com/rhel/defconfig/gcc/5.16.2-v5.16-amdsos/0/
	
	6. Run ncompare:
	[root@dellj853host LKP]# lkp ncompare -s commit=5.15.2-v5.15-amdsos -s commit=5.16.2-v5.16-amdsos -a -k
	Traceback (most recent call last):
	        10: from /home/LKP/lkp-tests/sbin/ncompare:6:in `<main>'
	         9: from /home/LKP/lkp-tests/lib/compare.rb:1150:in `compare'
	         8: from /home/LKP/lkp-tests/lib/compare.rb:1140:in `parse_argv'
	         7: from /home/LKP/lkp-tests/lib/compare.rb:1140:in `map'
	         6: from /home/LKP/lkp-tests/lib/compare.rb:1142:in `block in parse_argv'
	         5: from /home/LKP/lkp-tests/lib/compare.rb:1142:in `to_a'
	         4: from /home/LKP/lkp-tests/lib/nresult_root.rb:391:in `each'
	         3: from /home/LKP/lkp-tests/lib/nresult_root.rb:391:in `each'
	         2: from /home/LKP/lkp-tests/lib/nresult_root.rb:392:in `block in each'
	         1: from /home/LKP/lkp-tests/lib/nresult_root.rb:383:in `block in each'
	/home/LKP/lkp-tests/lib/data_store.rb:753:in `each': undefined method `each' for nil:NilClass (NoMethodError)

**Comment by xilabao** [comment]
@bssrikanth I can't reproduce it, can you remove the whole directory "/lkp/data/mresult_root/" and try again?

**Comment by bssrikanth** [comment]
> @bssrikanth I can't reproduce it, can you remove the whole directory "/lkp/data/mresult_root/" and try again?

@xilabao that worked.. 
```
Removed whole mresult_root folder, and then ran hackbench on 2 kernel levels:

[root@dellj853host LKP]# lkp ncompare -s commit=5.15.2-v5.15-amdsos -s commit=5.16.2-v5.16-amdsos -a -k
=========================================================================================
compiler/ipc/iterations/kconfig/mode/nr_threads/rootfs/tbox_group/testcase:
  gcc/socket/1/defconfig/threads/1600%/rhel/dellj853host.amd.com/hackbench

commit:
  5.15.2-v5.15-amdsos
  5.16.2-v5.16-amdsos

5.15.2-v5.15-amd         5.16.2-v5.16-amdsos
---------------- ---------------------------
         %stddev     %change         %stddev
             \          |                \
    275907           +10.9%     306109        hackbench.throughput
```

Question: we have few runs of benchmarks which we had done with older version of LKP, is there a way to port them to new layout/changes done recently in LKP?

**Comment by xilabao** [comment]
> Question: we have few runs of benchmarks which we had done with older version of LKP, is there a way to port them to new layout/changes done recently in LKP?

1. remove /lkp/paths (optional) to avoid duplicate paths in the output of command `lkp rt`
2. run `lkp merge /lkp/result` to generate new data for old results.
