### ISSUE TITLE
Testing blocked by an issue from time.rb

### ISSUE THREAD

**Issue by SCHEN2015** [intel/lkp-tests#17]
While testing with CentOS 7.5, I encountered the following issue which has blocked the report from generating.

# Description
```
/usr/share/ruby/time.rb:264:in `local': argument out of range (ArgumentError)
```

# Debug Log
```
......
wait for background monitors: 22739 22791 22793 22854 22799 22804 22895 22839 22810 22889 uptime proc-vmstat proc-stat diskstats meminfo slabinfo sched_debug softirqs interrupts turbostat
/usr/share/ruby/time.rb:264:in `local': argument out of range (ArgumentError)
	from /usr/share/ruby/time.rb:264:in `make_time'
	from /usr/share/ruby/time.rb:331:in `parse'
	from /root/lkp/lkp-tests/stats/mpstat:25:in `parse_time'
	from /root/lkp/lkp-tests/stats/mpstat:44:in `block in <main>'
	from /root/lkp/lkp-tests/stats/mpstat:37:in `each_line'
	from /root/lkp/lkp-tests/stats/mpstat:37:in `<main>'
2018-09-18 07:41:27 ERROR -- /root/lkp/lkp-tests/stats/mpstat /lkp/result/hackbench/50%-threads-socket/ip-10-22-2-38.us-west-2.compute.internal/centos/x86_64-rhel-7.2/gcc-7/4.9.112-32.el7.x86_64/0/mpstat < /lkp/result/hackbench/50%-threads-socket/ip-10-22-2-38.us-west-2.compute.internal/centos/x86_64-rhel-7.2/gcc-7/4.9.112-32.el7.x86_64/0/mpstat  exit code 1, check /dev/shm/lkp-stats.RGn0CrLi
```

And there is no outputs can be found in /dev/shm/lkp-stats.RGn0CrLi.

# How reproducible
100%

# Step to reproduce
```
lkp install --ssd /dev/xvdb --hdd /dev/xvdc
lkp split-job lkp-tests/jobs/hackbench.yaml
lkp install ./hackbench-50%-threads-socket.yaml
lkp run ./hackbench-50%-threads-socket.yaml
```
# Version-Release number of selected component
```
[root@ip-10-22-2-38 lkp]# cat /etc/system-release
CentOS Linux release 7.5.1804 (Core) 
[root@ip-10-22-2-38 lkp]# uname -r
4.9.112-32.el7.x86_64
[root@ip-10-22-2-38 lkp]# ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
[root@ip-10-22-2-38 lkp]# gem list

*** LOCAL GEMS ***

ast (2.4.0)
bigdecimal (1.2.0)
builder (3.2.3)
bundler (1.16.4)
ci_reporter (2.0.0)
ci_reporter_rspec (1.0.0)
coderay (1.1.2)
colorize (0.8.1)
diff-lcs (1.3)
docile (1.3.1)
git (1.5.0)
gnuplot (2.6.2)
io-console (0.4.2)
json (2.1.0, 1.7.7)
method_source (0.9.0)
parallel (1.12.1)
parser (2.5.1.2)
powerpack (0.1.2)
pry (0.11.3)
pry-doc (0.13.4)
psych (2.0.0)
rainbow (2.2.2)
rake (12.3.1)
rdoc (4.0.0)
rspec (3.8.0)
rspec-core (3.8.0)
rspec-expectations (3.8.1)
rspec-mocks (3.8.0)
rspec-support (3.8.0)
rubocop (0.50.0)
ruby-progressbar (1.10.0)
simplecov (0.16.1)
simplecov-html (0.10.2)
simplecov-rcov (0.2.3)
term-ansicolor (1.6.0)
tins (1.16.3)
unicode-display_width (1.4.0)
yard (0.9.16)
```

# Additional information
1. This problem can also be reproduced on RHEL7.5.

**Comment by SCHEN2015** [comment]
Yes, I can reproduce it by this command.
```
[root@ip-10-22-2-38 lkp]# /root/lkp/lkp-tests/stats/mpstat /lkp/result/hackbench/50%-threads-socket/ip-10-22-2-38.us-west-2.compute.internal/centos/x86_64-rhel-7.2/gcc-7/4.9.112-32.el7.x86_64/0/mpstat < /lkp/result/hackbench/50%-threads-socket/ip-10-22-2-38.us-west-2.compute.internal/centos/x86_64-rhel-7.2/gcc-7/4.9.112-32.el7.x86_64/0/mpstat
/usr/share/ruby/time.rb:264:in `local': argument out of range (ArgumentError)
	from /usr/share/ruby/time.rb:264:in `make_time'
	from /usr/share/ruby/time.rb:331:in `parse'
	from /root/lkp/lkp-tests/stats/mpstat:25:in `parse_time'
	from /root/lkp/lkp-tests/stats/mpstat:44:in `block in <main>'
	from /root/lkp/lkp-tests/stats/mpstat:37:in `each_line'
	from /root/lkp/lkp-tests/stats/mpstat:37:in `<main>'
[root@ip-10-22-2-38 lkp]# 
```

**Comment by zhijianli88** [comment]
the mpstat format we expects should be:
```
$ cat mpstat
Linux 4.19.0-rc3 (lkp-skl-2sp2) 	2018-09-18 	_x86_64_	(80 CPU)
07:48:37     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
07:48:38     all    0.27    0.00    1.22    0.01    0.00    0.00    0.00    0.00    0.00   98.50
07:48:39     all    0.06    0.00    0.22    0.00    0.00    0.15    0.00    0.00    0.00   99.56
07:48:40     all    3.53    0.00    4.99    0.00    0.00    0.79    0.00    0.00    0.00   90.68
07:48:41     all    4.15    0.00    5.89    0.00    0.00    0.64    0.00    0.00    0.00   89.32
07:48:42     all    4.12    0.00    6.04    0.00    0.00    0.64    0.00    0.00    0.00   89.19
07:48:43     all    4.11    0.00    6.00    0.00    0.00    0.64    0.00    0.00    0.00   89.25
07:48:44     all    4.03    0.00    6.09    0.01    0.00    0.63    0.00    0.00    0.00   89.24
07:48:45     all    1.75    0.00    6.80    5.05    0.00    0.79    0.00    0.00    0.00   85.61
```

could you list part of yours
